name: YouTube Live
on: workflow_dispatch

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Faylni yuklab olish
        run: wget -O video.mp4 "https://github.com/wiithreee-ops/congenial-invention/releases/download/v1.0/live.mp4"
      
      - name: FFmpeg o'rnatish
        run: sudo apt update && sudo apt install -y ffmpeg
      
      - name: Jonli efirni boshlash
        run: |
          while true; do
            ffmpeg -re -stream_loop -1 -i video.mp4 -c copy -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}"
            echo "Efir uzildi, qayta ulanmoqda..."
            sleep 5
          done
